name: Build java with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  REGISTRY: ghcr.io
  
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run:  mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/vanessa-ivanov/SimpleApp

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Push Docker Image
      run: |
        docker push ${{ env.REGISTRY }}/vanessa-ivanov/SimpleApp
  
